# Generated by Django 5.2.5 on 2025-08-10 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_duration_minutes_event_end_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Mark this event as manually completed'),
        ),
    ]
