# Generated by Django 5.2.5 on 2025-08-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_complete_datetime',
            field=models.DateTimeField(blank=True, help_text='Event will be automatically marked as completed at this date and time', null=True),
        ),
    ]
