# Generated by Django 5.2.5 on 2025-08-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_auto_complete_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='auto_complete_days',
            field=models.PositiveIntegerField(default=0, help_text='Days after event start to auto-complete'),
        ),
        migrations.AddField(
            model_name='event',
            name='auto_complete_hours',
            field=models.PositiveIntegerField(default=0, help_text='Hours after event start to auto-complete'),
        ),
    ]
