# Generated by Django 5.2.5 on 2025-08-10 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_auto_complete_days_event_auto_complete_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='event',
            name='duration_days',
            field=models.PositiveIntegerField(default=0, help_text='Duration in days'),
        ),
        migrations.AddField(
            model_name='event',
            name='duration_hours',
            field=models.PositiveIntegerField(default=0, help_text='Duration in hours'),
        ),
    ]
