# Generated by Django 5.2.5 on 2025-08-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_avatar'),
        ('accounts', '0002_fix_default_avatar_paths'),
    ]

    operations = [
    ]
