# Generated by Django 5.2.5 on 2025-08-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_remove_event_duration_minutes_event_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event_pics/event_default.png', upload_to='event_pics'),
        ),
    ]
