# Generated by Django 5.2.5 on 2025-08-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_image'),
        ('events', '0007_fix_default_event_image_paths'),
    ]

    operations = [
    ]
